apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  namespace: middle
  labels:
    app: blog  
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: blog 
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
        - name: wordpress
          image: wordpress:latest  
          env:
            - name: WORDPRESS_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap  
                  key: user  
            - name: WORDPRESS_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap 
                  key: database  
            - name: WORDPRESS_DB_HOST
              value: "mysql-service.database.svc.cluster.local"  
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret  
                  key: password  
          ports:
            - containerPort: 80  
          volumeMounts:  
            - name: wordpress-storage
              mountPath: /var/www/html  
      volumes:  
        - name: wordpress-storage
          persistentVolumeClaim:
            claimName: wordpress-pvc 
