apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  namespace: middle
spec:
  accessModes:
    - ReadWriteMany  
  resources:
    requests:
      storage: 100Mi  
  storageClassName: manual 
  volumeName: wordpress-pv
