apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: middle
spec:
  selector:
    app: blog  
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 80  
  type: ClusterIP  
