apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
  namespace: database
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: mysql  
  serviceName: "mysql"
  template:
    metadata:
      labels:
        app: mysql  
    spec:
      containers:
      - name: mysql
        image: mysql:8.0  
        ports:
        - containerPort: 3306 
        env:
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: mysql-configmap
              key: user 
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-configmap
              key: database  
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password  
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: rootpassword  
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql  
  volumeClaimTemplates:
  - metadata:
      name: mysql-persistent-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi  
